# Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "daniel",
  "email": "gamesmy177@gmail.com",
  "password": "password123",
  "role": "user"
}

###

# Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "gamesmy177@gmail.com",
  "password": "password123"
}