# Create a new event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "title": "Iphone 16 Launch",
  "description": "Be the first to use the latest Iphone",
  "date": "2024-08-01T19:00:00.000Z",
  "location": "Apple Gaming Arena",
  "ticketPrice": 100.0,
  "image": "https://i.pinimg.com/564x/c3/09/c3/c309c34a7901c8a38702d482ef421f15.jpg",
  "organizerId": 2
}

### Get all events
GET http://localhost:3000/api/events

### Get event by ID
GET http://localhost:3000/api/events/1

### Update Event
PUT http://localhost:3000/api/events/1003
Content-Type: application/json

{
  "title": "Crypto Conference",
  "description": "Learn about the future of money",
  "date": "2024-08-15T12:00:00.000Z",
  "location": "Times Tower",
  "ticketPrice": 500,
  "image": "https://i.pinimg.com/564x/81/78/4e/81784e304f80f3f9801d17335717ea13.jpg"
}

### Delete Event
DELETE http://localhost:3000/api/events/3003

### Get Event Statistics for Organizer
GET http://localhost:3000/api/events/statistics/1

### Get Event Statistics for a Specific Event
GET http://localhost:3000/api/events/statistics/event/1

### Get Event Statistics for All Events
GET http://localhost:3000/api/events/statistics
